version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - cargo-cache:/usr/local/cargo
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    command: ["cargo", "watch", "-x", "run"]
    networks:
      - backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oxidrive_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  cargo-cache:
